### PR TITLE
Shops 2: Electric Boogaloo

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
GOD THE COMMIT VOMIT HOW DO I FIX THAT

### CODE REVIEW

**Comment by ThePythonGuy3** [comment]
sowwy :(

**Comment by NiChrosia** [comment]
> GOD THE COMMIT VOMIT HOW DO I FIX THAT

force pushing

**Comment by ThePythonGuy3** [comment]
what

**Comment by SMOLKEYS** [comment]
~~will i be part of the contributors?~~

**Comment by ThePythonGuy3** [comment]
k done

**Comment by MEEPofFaith** [comment]
There's a reason "Squash and Merge" is an option when someone merges a pull request.

**Comment by ThePythonGuy3** [comment]
> There's a reason "Squash and Merge" is an option when someone merges a pull request.

oh thank god

**Pull request merged**
