### PR TITLE
Item Shop (Part 1 of Mindblow port)

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *screams more* AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Yes.

### CODE REVIEW

**Comment by ThePythonGuy3** [comment]
Commit vomit go brrrrrrrrrrr

**Review by sk7725 — CHANGES_REQUESTED** [review]
- why change the box icon?
- why change the tensor item color?
- remove classes.dex

**Comment by SMOLKEYS** [comment]
amazing

**Comment by NewestGitHubber** [comment]
amazing

**Comment by MQ18112005** [comment]
amazing

**Comment by MrAntlrr** [comment]
amazing

**Comment by lokyinng** [comment]
amazing

**Comment by QmelZ** [comment]
haha chain go bye bye

**Comment by ThePythonGuy3** [comment]
> * why change the box icon?
> * why change the tensor item color?
> * remove classes.dex

> woops
> ~looked like poo but I honestly forgot I did that~
> woops

**Comment by ThePythonGuy3** [comment]
k done

**Comment by ThePythonGuy3** [comment]
yay

**Comment by lokyinng** [comment]
yay

**Pull request merged**
