### PR TITLE
Make stuff only purchasable in sandbox or when its unlocked

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
image

### CODE REVIEW

**Comment by sk7725** [comment]
Nice ~~and also did you summon your trading post code from the depths of hell~~?
(I'm fixing the trading posts, dont worry)

**Comment by ThePythonGuy3** [comment]
lmfao

**Comment by notMEEPoffaith** [comment]
forgien stuff

**Comment by notMEEPoffaith** [comment]
also when tree farms

**Pull request merged**
