### PR TITLE
small update

### PR DESCRIPTION
**Pull request by TheEE145**
1. fixed exceptions when multiTurret was shoot (IllegalException and NullPointerException)
2. update mindustry core to 141 (and it works on 138)
3. added repo in the mod.json

### CODE REVIEW

**Comment by Slotterleet** [comment]
~~why MindustryJitpack over Mindustry~~

**Comment by TheEE145** [comment]
in v138 and hinger Mindustry replaced to MindustryJitpack

**Comment by Slotterleet** [comment]
Mindustry works fine for me

**Comment by SMOLKEYS** [comment]
> in v138 and hinger Mindustry replaced to MindustryJitpack

no

MindustryJitpack was made because jitpack can be a Piece Of Shit™️ when it comes to accessing it

its practically a secondary mirror for when the primary one stops working

**Comment by TheEE145** [comment]
but jitpack more stable

**Comment by Slotterleet** [comment]
Jitpack isn't gonna be stable anytime soon.

**Pull request closed without merging**
