### PR TITLE
topRegion For PayloadTurret

### PR DESCRIPTION
**Pull request by Voz-Duh**
For _texture pack_
image

### CODE REVIEW

**Comment by sk7725** [comment]
see ProcessorCooler.java; drawTop should be assigned automatically

**Comment by Voz-Duh** [comment]
> see ProcessorCooler.java; drawTop should be assigned automatically

Okay

**Comment by Voz-Duh** [comment]
@sk7725 done

**Comment by sk7725** [comment]
implemented it myself.

**Pull request closed without merging**
