### PR TITLE
[bundle]Russian Bundle For README

### PR DESCRIPTION
**Pull request by Voz-Duh**

### CODE REVIEW

**Comment by sk7725** [comment]
Move the russian translation below the korean.   
(Reason: Alphabetical order)   

Do note that I will not be receiving bundle translations from languages other than russian and korean, as they will be redundant and make the README longer than it should be.    
Russian and Korean are there because :
RU: Anuke's country, majority of players' native language   
KO: My country, ~~and where I spam BetaMindy ads~~

**Comment by GlennFolker** [comment]
racist
unstarred

**Comment by Goobrr** [comment]
smh smh

**Comment by GlennFolker** [comment]
You didn't really have to put whatever languages in the README.md anyway, all programmers should know what [English](https://en.wikipedia.org/wiki/English_language) is

**Comment by Gdeft** [comment]
$ sudo apt install man
$ man english

**Comment by sk7725** [comment]
> racist
> unstarred

restar or ~~I will terminate you~~

**Comment by Gdeft** [comment]
> > racist
> > unstarred
> 
> restar or ~I will terminate you~

Basically what's happening in sk's korean community right now.

**Comment by Voz-Duh** [comment]
> racist
> unstarred

I hate Russian, but I don't mind translating something into Russian, since I have knowledge of Russian, why not use what I know?

**Comment by GlennFolker** [comment]
> > racist
> > unstarred
> 
> I hate Russian, but I don't mind translating something into Russian, since I have knowledge of Russian, why not use what I know?

To be fair, I wasn't talking to you.

**Comment by Voz-Duh** [comment]
> > > racist
> > > unstarred
> > 
> > 
> > I hate Russian, but I don't mind translating something into Russian, since I have knowledge of Russian, why not use what I know?
> 
> To be fair, I wasn't talking to you.

Okay... /-/

**Comment by Voz-Duh** [comment]
@sk7725

**Comment by GlennFolker** [comment]
~~Do it properly: ~~ <@640020547396435989>

**Comment by sk7725** [comment]
> languages other than russian and korean

I said I will accept russian, I do admit my phrasing was a bit off

**Comment by GlennFolker** [comment]
i guess you don't get my point after all

**Comment by GlennFolker** [comment]
_All_ languages should be accepted, long ass `README.md` as a problem is ridiculous as you don't even need to explain how to compile in all languages anyway. After all, what kind of programmer that doesn't know English ?

**Comment by GlennFolker** [comment]
... GitHub thread probably isn't the best place to discuss this

**Comment by Gdeft** [comment]
> what kind of programmer that doesn't know English?
The kind who doesn't know English. Also, nice use of the space before the question mark, very English.

**Comment by GlennFolker** [comment]
> The kind who doesn't know English
Well good luck finding one

**Pull request merged**
