### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by Prosta4okua**

### CODE REVIEW

**Comment by Prosta4okua** [comment]
There is a problem with ʼ (\u02bc). The character doesn't display in the game.
@sk7725

**Comment by Prosta4okua** [comment]
Also maybe you need to create different `Readme.md` for every language? Or I need to add Ukrainian translation to `Readme.md`?

**Comment by Prosta4okua** [comment]
What do you think, @sk7725?

**Comment by sk7725** [comment]
nice!

**Review by sk7725 — CHANGES_REQUESTED** [review]
Read the original bundle's comments; they tell you which line to omit from the bundle entirely.

+ the codev, contributors, and musics line should be deleted, for example

**Comment by Prosta4okua** [comment]
> Read the original bundle's comments; they tell you which line to omit from the bundle entirely.
> 
> * the codev, contributors, and musics line should be deleted, for example

```
# suppress inspection "UnusedProperty" for whole file
mod.betamindy.name = [accent]Beta[][white]Mindy[]
mod.betamindy.short = [#b59e72]Demo of Chaos Itself[]
mod.betamindy.description = My first [accent]Java[] mod, has the same amount of chaotic energy of [cyan]sk7725/Commandblocks[].
mod.codev = Co-Dev
mod.contributors = Contributors
mod.musics = Music
# Please do not translate the line below, as it will cease to update.
mod.betamindy.credits = [coral]{0}[]: Sharlotte\n[green]{1}[]: GlennFolker, EyeofDarkness, younggam, Voz-Duh, Rayforce, Red, Kapzduke, BasedUser, Buthed0203, ThePythonGuy3, Goober, MrDuck\n\n[pink]{2}[]\nSweet Self Satisfaction - RoccoW\nInvasion - FarmerThanos
```
Are you talking about the last line or also about any mod.* line?

**Comment by sk7725** [comment]
oh I am so sorry, only the last line, i was confused because the translation was long, i thougnt those were sentences.

**Comment by Prosta4okua** [comment]
@sk7725 👀 
https://github.com/sk7725/BetaMindy/pull/134#issuecomment-1019935145
https://github.com/sk7725/BetaMindy/pull/134#issuecomment-1019922386

**Comment by sk7725** [comment]
I think that character just does not exist within mindustry's font sheet. Does it display for vanilla translations?

**Comment by Prosta4okua** [comment]
> I think that character just does not exist within mindustry's font sheet. Does it display for vanilla translations?

Yes, you are right. I'm sorry

**Comment by Prosta4okua** [comment]
fixed

**Pull request merged**
