### PR TITLE
Shops Update

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
Changes:
- Fixed shops researching only being cosmetic
- Fixed payload visual error in item shops
- Fixed unit scoring
- Fixed label wrapping
- Fixed package2 being overriden
- Added research to packages
- Added search bars
- Added 2 more packages with their respective bundle entries
- Added bundle description for block-related packages
- Removed hasItems from shops
- Made package structure different
- Made UnitLib loading global (Don't yell at me just look at dms)
- Made black items be displayed as lightGray instead (I'm looking at you blue)
- First Aids -> First Aid (Correct form)
- Reduced padRight on anucoin icon for shop ui (10f -> 6f)
- Gray tree icons
- Rounded package prices to nearest 100 - 1 (not applied to prices <500)

### CODE REVIEW

**Comment by sk7725** [comment]
can you add the techtree icon to the Block/Item/LiquidItems too?

**Comment by ThePythonGuy3** [comment]
i'll try

**Review by sk7725 — CHANGES_REQUESTED** [review]
> src/betamindy/type/shop/ShopItem.java
- why does this add like 2 spaces? No spaces before or after brackets, except class definitions.

> src/betamindy/world/blocks/storage/Shop.java
- you cannot just omit `hasItems` as it will break saves.

**Comment by ThePythonGuy3** [comment]
- Intellij go brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
- Indeed, but none have items, and im not just gonna remove a Bar because of items, shops are WIP either way

**Comment by ThePythonGuy3** [comment]
- Fixed
- U sure abt that

**Comment by SMOLKEYS** [comment]
moment

**Pull request merged**
