### PR TITLE
chmod +x gradlew

### PR DESCRIPTION
**Pull request by DeltaNedas**
noob

### CODE REVIEW

**Comment by sk7725** [comment]
...I don't get it

**Comment by DeltaNedas** [comment]
on normal filesystems (not fat32) files can only be executed if they have the executable bit set.
this does that.

**Comment by sk7725** [comment]
image
...why is Github having a stroke
...I'll merge that tomorrow, its 2AM

**Comment by DeltaNedas** [comment]
644 -> 755 means executable bit (1) or'd

**Pull request merged**
